"""User-facing terminology and explanations shared by the web pages."""

FIELDS = {
    "compute_dtype": "Arithmetic precision: auto uses BF16 on NVIDIA or AMD GPUs with native support and FP32 on older GPUs or CPU. FP32 uses more memory but avoids unsupported BF16 operations.",
    "proof_size": "Laptop creates about 100M parameters with shorter examples; standard creates about 160M. Neither promises memory fit.",
    "model": "Model checkpoint directory or Hugging Face model ID. Advanced training can download a remote ID; the wizard requires a local checkpoint.",
    "source_model": "Local source checkpoint containing config.json, tokenizer files and safetensors weights. Use a separate output directory.",
    "student_model": "Checkpoint to update during recovery training.",
    "teacher_model": "Original checkpoint that supplied reasoning targets for recovery.",
    "adapter": "Directory of trained adapter weights to merge into the matching base model.",
    "bundle": "Packed artifact directory containing mixed-manifest.json, packed weights and research-hf. It is not a GGUF file.",
    "output_dir": "Directory for this stage’s outputs. Use a new directory for a new experiment; use the same directory and settings when resuming.",
    "output": "Output file path. Profiling writes JSON; GGUF calibration writes plain text.",
    "output_file": "Output JSONL file for generated teacher reasoning traces.",
    "output_name": "Filename of the generated GGUF model inside output_dir.",
    "dataset_name": "Hugging Face dataset ID. The container needs network access and any required read permission.",
    "dataset_config": "Named subset of the selected dataset, such as canonical. It must exist in that dataset.",
    "dataset_split": "Dataset partition to use, usually train. Keep benchmark content separate.",
    "dataset_path": "Local training data file. JSONL accepts text or conversational messages; supported advanced stages also accept Parquet.",
    "dataset": "JSONL recovery examples used to restore behavior after compression. Accepts text or messages.",
    "calibration_file": "Representative examples for quantization. B/C uses JSONL text records; the GGUF stage uses a plain-text corpus.",
    "heldout_file": "Separate JSONL text examples used only for evaluation, never training or calibration.",
    "prompts_file": "JSONL user prompts or messages without assistant answers. Used to generate teacher reasoning traces.",
    "recovery_dataset": "JSONL text or messages used for quantization-aware recovery training.",
    "benchmark_results": "JSON file of published benchmark scores, artifact hashes and harness revisions. See Help for the required evidence.",
    "cuda_devices": "Physical GPU IDs visible in System, separated by commas. Inside the selected process these become cuda:0, cuda:1, in this order.",
    "device": "Logical GPU within the selected set, usually cuda:0. Web proof runs require NVIDIA CUDA or AMD ROCm, not CPU.",
    "runtime_device": "Logical GPU for packed inference and context tests. These tests use one selected GPU.",
    "window_devices": 'Logical GPUs for layer reconstruction, for example ["cuda:0", "cuda:1"]. Use only devices exposed by cuda_devices.',
    "num_processes": "Training worker processes, normally one per selected GPU. Two processes do not combine GPU memory into one allocation.",
    "load_in_4bit": "Load the training source at 4-bit precision to reduce memory use. Training updates adapter weights.",
    "lora_rank": "Capacity of the small trainable adapters. Higher rank can learn more but uses more memory.",
    "expert_rank": "Adapter rank for routed expert weights. Smaller values reduce adapter memory across many experts.",
    "max_length": "Maximum tokens per training example. Longer examples use more memory. This does not change the model’s native context limit.",
    "max_prompt_tokens": "Maximum input length for teacher reasoning generation. Overlong prompts are rejected.",
    "max_new_tokens": "Maximum generated output tokens. Prompt plus output must fit within 262144 tokens.",
    "batch_size": "Examples processed together by each GPU. Start at 1 for large models.",
    "gradient_accumulation_steps": "Small batches accumulated before one optimizer update. Effective batch size is batch_size × processes × accumulation.",
    "learning_rate": "Size of weight updates. Larger values learn faster but can damage behavior. Keep the provided stage-specific default for a first run.",
    "num_train_epochs": "Passes through the training data. A positive max_steps overrides this budget.",
    "max_steps": "Maximum optimizer updates. In advanced SFT, -1 uses the epoch budget instead.",
    "train_steps": "Optimizer updates for the miniature proof’s initial training.",
    "reconstruct_steps": "Updates spent fitting each proof reconstruction window to the teacher’s outputs.",
    "qat_steps": "Updates for quantization-aware recovery, which trains with simulated low-precision weights.",
    "assistant_only_loss": "Train on assistant output tokens rather than the whole conversation. Requires a compatible chat template with assistant masks.",
    "max_samples": "Maximum data records to use. More records improve workload coverage but increase time and memory.",
    "samples": "Calibration records used by the miniature proof.",
    "profile": "Expert-usage JSON produced by the profiling stage. It must match the source checkpoint.",
    "keep_experts": "Experts retained in every layer. Must be below the original count and at least the number selected per token. Pruning can reduce quality.",
    "routing_mass_weight": "Weight from 0 to 1 given to routing probability versus selection frequency when ranking experts. 0.5 balances the two.",
    "quant_type": "llama.cpp weight format for GGUF output. Lower-bit formats save space and can reduce quality; backend support depends on the installed version.",
    "output_tensor_type": "GGUF precision for the output projection. Higher precision can protect output quality.",
    "token_embedding_type": "GGUF precision for token embeddings.",
    "imatrix_context": "Token length for importance-matrix calibration, which estimates which weights need precision.",
    "imatrix_gpu_layers": "Layers to place on the GPU for GGUF calibration. 999 requests all layers and may exceed memory.",
    "tensor_overrides": "List of parameter-name patterns with explicit GGUF precision overrides. Check supported types in the installed backend.",
    "pattern": "Regular expression matching parameter names. B/C sensitive rules use first-match priority; an unmatched sensitivity rule is rejected.",
    "type": "Backend-specific weight format for a matching tensor.",
    "bits": "Bit width for matching sensitive tensors. B/C sensitivity rules support GSQ 2 or 3 bits.",
    "preset": "aggressive uses 2-bit routed experts; extreme uses ternary routed experts and requires sensitive-tensor rules plus QAT recovery.",
    "engine": "upstream_window reconstructs outputs of one or more layers using pinned GSQ/CAT-Q sources. reference fits individual tensors and is an earlier research implementation.",
    "attention_bits": "3 or 4 bits for attention and other eligible non-expert tensors. More bits use more memory and may retain quality better.",
    "shared_bits": "3 or 4 bits for experts used by every token. These components often need more precision than routed experts.",
    "sensitive_tensors": "Parameter-name rules that give selected weights extra precision. Defaults are a hypothesis, not measured importance for your workload.",
    "group_size": "Weights sharing one quantization scale. Allowed B/C values: 32, 64 or 128. Smaller groups use more scale storage.",
    "window_size": "Layers optimized together during reconstruction. Larger windows use more memory.",
    "window_stride": "Layers advanced between reconstruction windows. Must be from 1 to window_size; smaller strides create overlap.",
    "steps": "Optimization updates for each reconstruction window or tensor fit. More steps increase run time.",
    "row_chunk": "Rows processed together in the reference tensor quantizer. Smaller chunks reduce temporary memory.",
    "chunk_rows": "Output rows decoded at once in packed inference. Smaller values reduce temporary memory but can be slower.",
    "calibration_length": "Maximum tokens per calibration record. It is not the final supported context length.",
    "context_length": "B/C native context target, fixed at 262144. This setting alone does not test that length.",
    "context_lengths": "Prompt lengths to test. Each prompt plus max_new_tokens must fit the native context budget.",
    "context_repeats": "Repeated needle-retrieval tests at each prompt length. Retrieval is a diagnostic, not a coding or agent benchmark.",
    "sequence_length": "Training and evaluation token length for the miniature proof. Short lengths keep the test small.",
    "eval_length": "Maximum tokens per held-out record for loss evaluation.",
    "eval_samples": "Held-out records to evaluate. These short diagnostic samples do not replace a published benchmark suite.",
    "max_memory": 'Per-logical-GPU and CPU loading allowances for the baseline. Example: {"0":"28GiB","cpu":"80GiB"}. This is not a hard cap on all runtime allocations.',
    "vram_limit_gib": "Pass/fail memory target for the final model, in GiB. It does not limit allocations or guarantee a fit on a physical 12GB card.",
    "checkpoint_steps": "Updates between saved reconstruction checkpoints. More frequent saves reduce lost work after interruption.",
    "save_steps": "Training updates between saved Trainer checkpoints.",
    "masks_lr": "Learning rate for low-bit assignment masks in upstream reconstruction.",
    "gptq_damp": "Damping added to the calibration matrix for stable GPTQ initialization.",
    "gptq_block_size": "Weight columns processed per GPTQ initialization block.",
    "catq_rank": "Rank of the small correction used by the experimental ternary reconstruction.",
    "catq_alpha": "Scale of the ternary reconstruction correction.",
    "seed": "Random seed recorded for reproducibility. Hardware can still affect numerical results.",
    "dry_run": "For supported stages, inspect inputs and write a plan without training or quantizing. It is not a memory, quality or full-run test.",
    "resume": "Continue the same run using saved state. Source, data, settings and implementation must match the original run.",
    "recovery": "Nested settings for quantization-aware training after reconstruction. The final weights are quantized again after recovery.",
    "enabled": "Enable the recovery stage. Mandatory for extreme compression.",
    "hidden_size": "Width of hidden activations in the synthetic proof model; a multiple of 64.",
    "layers": "Decoder layers in the synthetic proof model. Supported range: 3–16.",
    "experts": "Routed experts per proof-model layer. Supported range: 2–32.",
    "top_k": "Experts selected for each token in the proof model. Cannot exceed experts.",
    "expert_width": "Intermediate width of each proof expert; a multiple of 64.",
    "prompt": "Text to generate from. Generated code and tool calls are displayed, not executed.",
}

LABELS = {
    "aggressive": "Aggressive compression (B)",
    "extreme": "Extreme compression (C)",
    "checkpoint_restart": "Saved-checkpoint restart",
    "packed_export_parity": "Packed weights match the reference export",
    "vram_measured": "GPU memory was measured",
    "within_vram_limit": "Measured GPU memory meets the target",
    "needle_retrieval": "Secret-code retrieval from long prompts",
    "coding_tool_quality": "Coding and tool-use quality established",
    "miniature-proof": "Miniature workflow test",
    "sft": "Supervised fine-tuning",
    "merge": "Merge trained adapter",
    "profile": "Measure expert usage",
    "prune": "Remove selected experts",
    "ayot": "Generate teacher reasoning",
    "validation": "Evaluate compressed models",
    "benchmarks": "Run isolated benchmark suites",
    "automated_run": "Guided automated run",
    "proof_run": "Miniature workflow test",
    "full_validation": "Real-model compression and diagnostics",
    "packed_inference": "Generate from packed weights",
    "benchmark_compare": "Compare imported benchmark scores",
    "baseline": "Uncompressed reference evaluation",
    "bootstrap": "Initial model training",
    "generate": "Create synthetic model and data",
    "queued": "Waiting to start",
    "running": "Running",
    "stopping": "Stopping",
    "interrupted": "Interrupted",
    "succeeded": "Execution completed",
    "completed": "Execution completed",
    "failed": "Execution failed",
}


def human_label(value):
    text = str(value)
    if text in LABELS:
        return LABELS[text]
    suffixes = {
        "initial": "evaluation before recovery",
        "packed": "packed-weight evaluation",
        "qat": "quantization-aware recovery",
        "reconstruct": "initial reconstruction",
        "requantize": "quantize recovered weights",
        "pipeline": "compression and recovery",
    }
    for prefix in ("aggressive", "extreme"):
        if text.startswith(prefix + "-"):
            suffix = text[len(prefix) + 1 :]
            return LABELS[prefix] + ": " + suffixes.get(suffix, suffix.replace("-", " "))
    return text.replace("_", " ").replace("-", " ").capitalize()
